version: "3.8"

services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./server:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - PORT=3000
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/psycho_analysis
            - BOT_TOKEN=${BOT_TOKEN}
            - MISTRAL_API_KEY=${MISTRAL_API_KEY}
            - JWT_SECRET=${JWT_SECRET:-your-secret-key-for-development}
            - JWT_EXPIRES_IN=24h
        depends_on:
            - db
        command: npm run dev

    db:
        image: postgres:15
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=psycho_analysis
        volumes:
            - postgres_data:/var/lib/postgresql/data

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - ./client:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        command: npm run dev

volumes:
    postgres_data:
